export const LOADING = "LOADING";

export const TOPAIRTHEE ='TOPAIRTHEE'
export const TOPAIR ='TOPAIR'
export const TOPAIRTEN ='TOPAIRTEN'

export const RECENTTENJAP ='RECENTTENJAP'
export const RECENTALLJAP ='RECENTALLJAP'

export const RECENTTENDUB ='RECENTTENDUB'
export const RECENTALLDUB ='RECENTALLDUB'

export const RECENTTENCH ='RECENTTENCH'
export const RECENTALLCH ='RECENTALLCH'

export const MOVIESTEN ='MOVIESTEN'
export const MOVIESALL ='MOVIESALL'


export const POPULARTEN ='POPULARTEN'
export const PAPULARALL ='PAPULARALL'

export const ANIMEDETAIL ='ANIMEDETAIL'

export const WATCHANIME ='WATCHANIME'

export const SEARCHANIME ='SEARCHANIME'

export const SEARCHLODER ='SEARCHLODER'
export const GENERCE ='GENERCE'

